# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperatureConverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 75, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 75, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 160, 440, 40))
        self.lcdNumber.setInputMask("")
        self.lcdNumber.setMaxLength(15)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setReadOnly(True)
        self.txt_temperature = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.txt_temperature.setGeometry(QtCore.QRect(20, 15, 440, 40))
        self.txt_temperature.setObjectName("txt_temperature")
        self.cb_fromUnit = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fromUnit.setGeometry(QtCore.QRect(20, 100, 160, 22))
        self.cb_fromUnit.setCurrentText("")
        self.cb_fromUnit.setObjectName("cb_fromUnit")
        self.cb_toUnit = QtWidgets.QComboBox(self.centralwidget)
        self.cb_toUnit.setGeometry(QtCore.QRect(300, 100, 160, 22))
        self.cb_toUnit.setCurrentText("")
        self.cb_toUnit.setObjectName("cb_toUnit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.addValues()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.cb_fromUnit.currentTextChanged.connect(self.convert)
        self.cb_toUnit.currentTextChanged.connect(self.convert)
        self.txt_temperature.valueChanged.connect(self.convert)
        self.convert()

    def addValues(self):
        self.cb_fromUnit.addItem("Kelvin")
        self.cb_toUnit.addItem("Kelvin")
        self.cb_fromUnit.addItem("Celsius")
        self.cb_toUnit.addItem("Celsius")
        self.cb_fromUnit.addItem("Fahrenheit")
        self.cb_toUnit.addItem("Fahrenheit")
        self.cb_fromUnit.addItem("Rankine")
        self.cb_toUnit.addItem("Rankine")
        self.cb_fromUnit.addItem("Delisle")
        self.cb_toUnit.addItem("Delisle")
        self.cb_fromUnit.addItem("Newton")
        self.cb_toUnit.addItem("Newton")
        self.cb_fromUnit.addItem("Réamur")
        self.cb_toUnit.addItem("Réamur")
        self.cb_fromUnit.addItem("Romer")
        self.cb_toUnit.addItem("Romer")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature Converter"))
        self.label.setText(_translate("MainWindow", "From"))
        self.label_2.setText(_translate("MainWindow", "To"))

    def convert(self):
        unit = self.cb_toUnit.currentIndex()
        value = self.getBaseValue()
        if unit == 0:
            self.lcdNumber.setText(str(round(value,5))+" °")
        elif unit == 1:
            converted_value = value - 273.15
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 2:
            converted_value = (value*(9/5))-459.67
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 3:
            converted_value = value * (9/5)
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 4:
            converted_value = (373.15-value)*(3/2)
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 5:
            converted_value = (value-273.15) * (33/100)
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 6:
            converted_value = (value-273.15) * (4/5)
            self.lcdNumber.setText(str(round(converted_value,5))+" °")
        elif unit == 7:
            converted_value = ((value-273.15) * (21/40))+7.5
            self.lcdNumber.setText(str(round(converted_value,5))+" °")

    def getBaseValue(self):
        if self.txt_temperature.text() == '':
            value = 0
        else:
            value = float(self.txt_temperature.text())
        selection = self.cb_fromUnit.currentIndex()
        if selection == 0:
            converted_value = value
            return converted_value
        elif selection == 1:
            converted_value = value + 273.15
            return converted_value
        elif selection == 2:
            converted_value = (value+459.67) * (5/9)
            return converted_value
        elif selection == 3:
            converted_value = (value) * (5/9)
            return converted_value
        elif selection == 4:
            converted_value = 373.15 - (value * (2/3))
            return converted_value
        elif selection == 5:
            converted_value = (value*(100/33)) + 273.15
            return converted_value
        elif selection == 6:
            converted_value = (value*(5/4)) + 273.15
            return converted_value
        elif selection == 7:
            converted_value = (value-7.5)*(40/21)+273.15
            return converted_value

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())